byoc-nuon/README.md, byoc-nuon/src/components/clickhouse_cluster/outputs.tf
- **fix: ch cluster output**
- **docs: readme**
=> chore: ch cluster output fix

byoc-nuon/README.md, byoc-nuon/components/90-tf-clickhouse_cluster.toml, byoc-nuon/components/values/ctl-api.yaml
- **fix: clickhouse cluster branch**
- **chore: fix inputs**
- **readme: render inputs**
=> fix: ctl-api: fix inputs

byoc-nuon/README.md, byoc-nuon/actions/ctl_api_alb_healthcheck.toml, byoc-nuon/components/1-rds_cluster_nuon.toml, byoc-nuon/components/values/dashboard-ui.yaml, byoc-nuon/components/values/external-secrets.yaml, byoc-nuon/sandbox.toml
- **feat: alb healthcheck actions**
- **chore: update sandbox**
- **chore: use our image**
- **chore: revert**
- **docs: auth0**
- **chore: sandbox - point to prod nuon.run**
- **chore: update dash inputs**
=> chore: a suite of updates and the dashboard ui

byoc-nuon/README.md, byoc-nuon/actions/ch_cluster_creds.toml, byoc-nuon/actions/ch_operator_creds.toml, byoc-nuon/components/4-image-nuon_dashboard_ui.toml, byoc-nuon/components/90-tf-clickhouse_cluster.toml, byoc-nuon/components/values/ctl-api.yaml, byoc-nuon/components/values/dashboard-ui.yaml, byoc-nuon/src/components/clickhouse_cluster/cluster.tf
- **chore: dashboard-ui: update image**
- **chore: clickhouse: remove secret from tf**
- **chore: dashboard-ui: fix the issuer url**
- **feat: actions: ch cluster credentials**
- **chore: ctl-api: use clickhouse creds from secrets**
- **docs: update readme**
=> chore: remove tch secrets from state

byoc-nuon/actions/ctl_api_init.toml, byoc-nuon/components/92-helm-ctl_api.toml, byoc-nuon/sandbox.toml
- **chore: update the sandbox ref**
- **chore: update order of ctl-api-init-db action**
=> fix: ctl api init db: update dep order

byoc-nuon/inputs.toml, byoc-nuon/inputs/7-dns.toml, byoc-nuon/permissions.toml, byoc-nuon/sandbox.toml
- **chore: update sandbox version**
- **chore: add root_domain input**
- **chore: remove unused permissions from permissions toml**
=> chore: update sandbox, inputs, and perms

byoc-nuon/actions/nuon_rds_creds.toml, byoc-nuon/components/3-helm-ctl_api_init_db.toml, byoc-nuon/components/5-tf-temporal.toml, byoc-nuon/components/90-tf-clickhouse_cluster.toml, byoc-nuon/components/92-helm-ctl_api.toml
- **chore: make karpenter nodepools an explicit dependency**
- **fix: typo**
=> fix: typo and add deps

byoc-nuon/actions/temporal_init.toml, byoc-nuon/src/actions/temporal/init.sh
- **chore: remove unused var**
- **fix: better execution guarantees**
=> fix: temporal init action

byoc-nuon/actions/healthcheck_temporal.toml, byoc-nuon/actions/kill_pods_in_namespace.toml, byoc-nuon/actions/uninstall_helm_chart.toml
WIP, just realized this doesn't have an ALB so I can't use the standard action for this.
=> feat: temporal healthcheck

byoc-nuon/components/92-helm-ctl_api.toml, byoc-nuon/sandbox.toml
- **chore: add temporal to ctl-api deps**
- **chore: sb - remove var**
=> chore: ctl api: modifications

byoc-nuon/actions/preflight.toml, byoc-nuon/components/4-image-nuon_ctl_api.toml, byoc-nuon/components/92-helm-ctl_api.toml, byoc-nuon/components/values/ctl-api.yaml, byoc-nuon/src/actions/preflight/ensure-secrets-access.sh
- **feat: updated ctl-api**
- **chore: preflight - make generic**
- **chore: typo**
- **chore: ctl-api: deps**
- **chore: sandbox - remove kyverno policy dir**
=> chore: update ctl-api image

byoc-nuon/components/4-image-nuon_ctl_api.toml, byoc-nuon/components/values/ctl-api.yaml, byoc-nuon/src/components/s3_buckets/outputs.tf
- **chore: add region output**
- **chore: ctl-api: add a config var**
=> chore: bucket region

.github/sync.yml
- **ci: publish "main" action from main branch**
- **chore: manual workflow dispatch**
=> chore: automation

byoc-nuon/actions/ctl_api_init_db.toml, byoc-nuon/components/1-rds_cluster_nuon.toml, byoc-nuon/components/1-rds_cluster_temporal.toml, byoc-nuon/permissions.toml, byoc-nuon/permissions/maintenance_boundary.json, byoc-nuon/src/actions/ctl_api/init-db.sh, byoc-nuon/src/components/rds_cluster_nuon/.terraform.lock.hcl, byoc-nuon/src/components/rds_cluster_nuon/README.md, byoc-nuon/src/components/rds_cluster_nuon/data.tf, byoc-nuon/src/components/rds_cluster_nuon/main.tf, byoc-nuon/src/components/rds_cluster_nuon/outputs.tf, byoc-nuon/src/components/rds_cluster_nuon/providers.tf, byoc-nuon/src/components/rds_cluster_nuon/security_group.tf, byoc-nuon/src/components/rds_cluster_nuon/variables.tf, byoc-nuon/src/components/rds_cluster_nuon/versions.tf, byoc-nuon/src/components/rds_cluster_temporal/.terraform.lock.hcl, byoc-nuon/src/components/rds_cluster_temporal/README.md, byoc-nuon/src/components/rds_cluster_temporal/data.tf, byoc-nuon/src/components/rds_cluster_temporal/main.tf, byoc-nuon/src/components/rds_cluster_temporal/outputs.tf, byoc-nuon/src/components/rds_cluster_temporal/providers.tf, byoc-nuon/src/components/rds_cluster_temporal/security_group.tf, byoc-nuon/src/components/rds_cluster_temporal/variables.tf, byoc-nuon/src/components/rds_cluster_temporal/versions.tf, byoc-nuon/src/components/s3_buckets/install_templates_bucket.tf
- **chore: make some inputs internal**
- **chore: rds: import cluster components**
- **permissions: maintenance boundary**
=> chore: permissions and other refinements

byoc-nuon/policies.toml
- **fix: update policy to `kubernetes-cluster`**
- **fix: policy config type**
=> chore: update policy type

byoc-nuon/components/values/ctl-api.yaml, byoc-nuon/components/values/dashboard-ui.yaml
NOTE: this should be removed when the images start baking the value in
=> chore: add VERSION to configmap manually

byoc-nuon/actions/ctl_api_promote.toml, byoc-nuon/src/actions/ctl_api/migrations.sh
=> fix: ctl_api_promote script failing

byoc-nuon/actions/alb_healthcheck__api.toml, byoc-nuon/actions/alb_healthcheck__app.toml, byoc-nuon/actions/alb_healthcheck__runner.toml, byoc-nuon/actions/ctl_api_post_deploy.toml, byoc-nuon/actions/ctl_api_promote.toml, byoc-nuon/actions/healthcheck_temporal.toml
=> feat: slack notification when health checks fail

byoc-nuon/components/4-image-nuon_ctl_api.toml, changelog.md
=> chore: Update RT Dev to 596+hotfix

byoc-nuon/src/components/karpenter-nodepools/templates/nodepool.tpl, changelog.md
- **chore: karpenter: simplify budget for node disruption**
- **chore: changelog**
=> chore: karpenter simplify nodepool disruption budgest'

byoc-nuon/components/4-image-nuon_ctl_api.toml, byoc-nuon/components/4-image-nuon_dashboard_ui.toml, byoc-nuon/components/values/ctl-api.yaml, byoc-nuon/components/values/dashboard-ui.yaml, changelog.md
- **chore: remove unused vars - let container env provide these**
- **chore: release 0.19.601**
- **chore: changelog**
=> chore: release 0.19.601

byoc-nuon/components/values/ctl-api.yaml, changelog.md
- **chore: ctl-api: enable patcher middleware**
- **chore: changelog**
=> chore: ctl-api: enable patcher middleware

byoc-nuon/components/values/ctl-api.yaml
- **chore: enable force debug mode**
=> chore: enable force debug mode

byoc-nuon/components/4-image-nuon_ctl_api.toml, byoc-nuon/components/4-image-nuon_dashboard_ui.toml, changelog.md
- **chore: release 0.19.602**
- **chore: changelog**
=> chore: release 0.19.602

byoc-nuon/components/5-tf-temporal.toml, byoc-nuon/src/components/temporal/helm.tf, byoc-nuon/src/components/temporal/variables.tf
- **chore: src/temporal: simplify and clean up**
- **chore: src/temporal: set TEMPORAL_CODEC_ENDPOINT**
=> chore: temporal: add TEMPORAL_CODEC_ENDPOINT

byoc-nuon/src/components/karpenter-nodepools/templates/nodeclass.tpl
Use latest - 1 release of the AWS AMI.
=> chore: karpenter: update ami selector

byoc-nuon/actions/kubectl_delete_nodepool.toml, byoc-nuon/actions/kubectl_get_nodepool.toml, byoc-nuon/actions/kubectl_list_nodepools.toml
- **chore: new actions for karpenter nodepool debugging**
- **drop: sandbox version test**
=> feat: actions: for karpenter

byoc-nuon/components/0-karpenter_nodepools.toml, byoc-nuon/components/1-rds_cluster_nuon.toml, byoc-nuon/components/1-rds_cluster_temporal.toml
Add drift detection for karpenter nodepool and rds cluster to run every hour.
=> feat: add drift for karpenter nodepool and rds cluster
